name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Add remote
        run: |
          git remote add space https://M-Muddasir:${{ secrets.HF }}@huggingface.co/spaces/muddasir0096/assignment3

      - name: Push to hub
        run: |
          git push --force space main
